[build]
  command = "echo 'No build required'"
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.{js,css,jpg,jpeg,png,gif,svg}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
